### ISSUE TITLE
why there are more than 400 lines in `/usr/include/asm/unistd_32.h`?

### ISSUE THREAD

**Issue by wqreytuk** [mytechnotalent/Reverse-Engineering#2]

**Comment by wqreytuk** [comment]
https://0xinfection.github.io/reversing/pages/part-22-asm-program-1-moving-immediate-data.html
this are only totally 256 entries in Interrupt Vector Table, why there are more than 400 #define in this file?

**Comment by wqreytuk** [comment]
![image](https://user-images.githubusercontent.com/48377190/163543666-4be7ba59-4456-4c1e-a714-4d53daf576bc.png)

**Comment by mytechnotalent** [comment]
Are you looking at that version of Ubuntu's 32-bit version of the header?  It has grown since then with more modern versions.

**Comment by wqreytuk** [comment]
yes, I'm looking the exactly `/usr/include/asm/unistd_32.h`

**Comment by mytechnotalent** [comment]
Again the version of Ubuntu I had a few years back was different.  These are going to be different on different OS's and versions.  The point is understanding where to look and utilize them.
