### ISSUE TITLE
set constant = 666 won't work

### ISSUE THREAD

**Issue by wqreytuk** [mytechnotalent/Reverse-Engineering#3]
![image](https://user-images.githubusercontent.com/48377190/163553270-4130b66f-26c6-4afa-80fe-d70377388622.png)

**Comment by wqreytuk** [comment]
GDB version: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2

**Comment by mytechnotalent** [comment]
These lessons are a few years back so there will be some discrepancies unfortunately. At the time that is what worked however something like `set {int}constant = 666` or something along those lines.  I would try different combos.  These tools evolve with versions.

**Comment by wqreytuk** [comment]
> These lessons are a few years back so there will be some discrepancies unfortunately. At the time that is what worked however something like `set {int}constant = 666` or something along those lines. I would try different combos. These tools evolve with versions.

thanks for your patient reply, problem solved with this: https://sourceware.org/gdb/onlinedocs/gdb/Assignment.html
![image](https://user-images.githubusercontent.com/48377190/163664552-77fe3d35-09e2-4fac-a278-bd8669e0af42.png)

**Comment by mytechnotalent** [comment]
Great job @wqreytuk and my pleasure!
