### ISSUE TITLE
got errros when compile arm code

### ISSUE THREAD

**Issue by wqreytuk** [mytechnotalent/Reverse-Engineering#4]
I'm using Ubuntu 20

when I compile code in this section: https://0xinfection.github.io/reversing//pages/part-9-link-register.html

I got errors like this:

![image](https://user-images.githubusercontent.com/48377190/164408030-929eeb7c-135b-494c-a34a-6ad145b7da97.png)

**Comment by wqreytuk** [comment]
btw, there is a dead link here: https://0xinfection.github.io/reversing//pages/part-1-the-meaning-of-life.html

this link will lead me to a 404:[https://github.com/mytechnotalent/hacking\_c-\_arm64](https://github.com/mytechnotalent/hacking/_c-/_arm64)

**Comment by wqreytuk** [comment]
seems like the source code is not recognized by as

**Comment by mytechnotalent** [comment]
You are using a potential 64-bit version of the OS.  As I have said you need to search for commands that will be compatible.  OS evolve and the flags you pass to as will slightly deviate.  I can't keep up with all of the changes there are some things you will have to search around for but the code will compile.

**Comment by wqreytuk** [comment]
seems like it is because I'm using intel CPU

**Comment by mytechnotalent** [comment]
You have to read all of the instructions this is an ARM course and I use a Raspberry PI.  Please take some time and read all of the instructions.

**Comment by wqreytuk** [comment]
emmm... In fact, you didn't mention that in: https://0xinfection.github.io/reversing//pages/part-1-the-meaning-of-life.html

you mentioned it here:https://0xinfection.github.io/reversing//pages/part-1-the-meaning-of-life-part-2.html

so I didn't notice that at the beginning

**Comment by wqreytuk** [comment]
anyway, thanks for your reply and your great tutorial
