### ISSUE TITLE
x86: Segfault on EIP address change - chapter 12

### ISSUE THREAD

**Issue by Fabxx** [mytechnotalent/Reverse-Engineering#7]
Hi, first of all thank you for this tutorial. I've been following the chapter 12 and i did the steps showcased for the EIP register and how to exchange the simple printf function in main with another function not accessible. However, in my case this leads to a segfault and does not show  the expected output, here's what i did:

-Write a simple C program with main and  a void function not called in main

-Compile the code with vs code and gcc with these flags from make:
```CFLAGS	:= -Wall -Wextra -g -m32```

-use gdb on main, break main, run and display EIP instruction address

-disas of my custom function and retreived the first address of the stack (far left address)

-replace EIP address with the one from the stack needed.

-Continue and SIGSEGV

this is the actual code:
```
#include <stdio.h>

void func()
{
    printf("replaced EIP address.");
}

int main(void)
{
    printf("Hello World!\n");
    return 0;
}
```

here's a log with the disas info, EIP info and segfault info, using gef for extra details:

[log.txt](https://github.com/mytechnotalent/Reverse-Engineering/files/12513706/log.txt)

**Comment by mytechnotalent** [comment]
Not sure why you are getting the segfault you can try `gcc -m32 -o myprogram main.c -Wall -Wextra -g`.

**Comment by Fabxx** [comment]
> 

thank you for the response, unfortunately even if i compile from the terminal i still get the segfault

**Comment by mytechnotalent** [comment]
You might be jumping to an invalid address.
`set $eip = 0x5655619d`
Just single step it.
